services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_notes
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/notes
    depends_on:
      - mongodb
    networks:
      - my-network

  mongodb:
    image: mongo:latest
    container_name: database_notes
    command: mongod --logpath /var/log/mongodb/mongod.log --logappend --quiet --setParameter logLevel=2
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - my-network


volumes:
  mongo-data:

networks:
  my-network:
    driver: bridge
